name: dynamic_json
description: Retrieves the value from inside the JSON/Map using dot operator.
version: 0.0.1
homepage: https://www.example.com
author: marsa-emreef <marsa.emreef@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
